apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: llm-ops-postgres
  name: llm-ops-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: llm-ops-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/dp-llm-ops-default: "true"
        io.kompose.service: llm-ops-postgres
    spec:
      containers:
        - env:
            - name: PGDATA
              value: /var/lib/postgresql/data/db-files/
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: 165463520094.dkr.ecr.ap-northeast-1.amazonaws.com/cache-docker-hub/library/postgres:15-alpine3.17
          livenessProbe:
            exec:
              command:
                - pg_isready -U postgres
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 5
          name: llm-ops-postgres
          ports:
            - containerPort: 5432
              hostPort: 5433
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      restartPolicy: Always
      tolerations:
        - key: nodepool-version.spaas.smartnews.net/v2
          operator: Exists
          effect: NoSchedule
        - key: addon.spaas.smartnews.net/datadog
          operator: Exists
          effect: NoSchedule
        - key: pricing.spaas.smartnews.net/ondemand
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        nodepool-version.spaas.smartnews.net/v2: "true"
        addon.spaas.smartnews.net/datadog: "true"
        kubernetes.io/arch: "amd64"
        pricing.spaas.smartnews.net/ondemand: "true"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
