apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./proxy.yaml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: llm-ops-console
  name: llm-ops-console
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: llm-ops-console
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./proxy.yaml
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/dp-llm-ops-default: "true"
        io.kompose.service: llm-ops-console
    spec:
      containers:
        - env:
            - name: NX_BASE_API_URL
              valueFrom:
                configMapKeyRef:
                  key: NX_BASE_API_URL
                  name: llm-ops-console-env
            - name: NX_DEBUG_MODE
              valueFrom:
                configMapKeyRef:
                  key: NX_DEBUG_MODE
                  name: llm-ops-console-env
            - name: NX_SUPERTOKENS_API_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: NX_SUPERTOKENS_API_DOMAIN
                  name: llm-ops-console-env
            - name: NX_SUPERTOKENS_WEBSITE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: NX_SUPERTOKENS_WEBSITE_DOMAIN
                  name: llm-ops-console-env
          image: llm-ops-console:latest
          name: llm-ops-console
          ports:
            - containerPort: 4200
              hostPort: 4200
              protocol: TCP
      restartPolicy: Always
      tolerations:
        - key: nodepool-version.spaas.smartnews.net/v2
          operator: Exists
          effect: NoSchedule
        - key: addon.spaas.smartnews.net/datadog
          operator: Exists
          effect: NoSchedule
        - key: pricing.spaas.smartnews.net/ondemand
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        nodepool-version.spaas.smartnews.net/v2: "true"
        addon.spaas.smartnews.net/datadog: "true"
        kubernetes.io/arch: "amd64"
        pricing.spaas.smartnews.net/ondemand: "true"
