apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: llm-ops-redis-stack-server
  name: llm-ops-redis-stack-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: llm-ops-redis-stack-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/dp-llm-ops-default: "true"
        io.kompose.service: llm-ops-redis-stack-server
    spec:
      containers:
        - image: 165463520094.dkr.ecr.ap-northeast-1.amazonaws.com/cache-docker-hub/redis/redis-stack-server:7.2.0-v0
          livenessProbe:
            exec:
              command:
                - redis-cli ping | grep PONG
            failureThreshold: 5
            periodSeconds: 1
            timeoutSeconds: 3
          name: llm-ops-redis-stack-server
          ports:
            - containerPort: 6379
              hostPort: 6379
              protocol: TCP
      restartPolicy: Always
      tolerations:
        - key: nodepool-version.spaas.smartnews.net/v2
          operator: Exists
          effect: NoSchedule
        - key: addon.spaas.smartnews.net/datadog
          operator: Exists
          effect: NoSchedule
        - key: pricing.spaas.smartnews.net/ondemand
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        nodepool-version.spaas.smartnews.net/v2: "true"
        addon.spaas.smartnews.net/datadog: "true"
        kubernetes.io/arch: "amd64"
        pricing.spaas.smartnews.net/ondemand: "true"
