apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: pezzo-clickhouse-migrate
  name: pezzo-clickhouse-migrate
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pezzo-clickhouse-migrate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/dp-llm-ops-default: "true"
        io.kompose.service: pezzo-clickhouse-migrate
    spec:
      containers:
        - args:
            - -c
            - ./migrate.sh
          command:
            - /bin/sh
          env:
            - name: CLICKHOUSE_HOST
              value: smartnews-ops-0038ca8724e37848.elb.ap-northeast-1.amazonaws.com
            - name: CLICKHOUSE_PASSWORD
              value: FyaNO3kQRJNUU5bl
            - name: CLICKHOUSE_PORT
              value: "8123"
            - name: CLICKHOUSE_USER
              value: llm_ops_sa
          image: llm-ops-server:latest
          name: pezzo-clickhouse-migrate
          workingDir: /app/clickhouse
      restartPolicy: Always
      tolerations:
        - key: nodepool-version.spaas.smartnews.net/v2
          operator: Exists
          effect: NoSchedule
        - key: addon.spaas.smartnews.net/datadog
          operator: Exists
          effect: NoSchedule
        - key: pricing.spaas.smartnews.net/ondemand
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        nodepool-version.spaas.smartnews.net/v2: "true"
        addon.spaas.smartnews.net/datadog: "true"
        kubernetes.io/arch: "amd64"
        pricing.spaas.smartnews.net/ondemand: "true"
